# Generated by Django 5.2 on 2026-01-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('lecture_hours', models.IntegerField()),
            ],
            options={
                'ordering': ['course_id'],
            },
        ),
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='imports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEANSING', 'Data Cleansing'), ('FORMATTING', 'Data Formatting'), ('IMPORTING', 'Importing Data'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('program', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
            ],
            options={
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='importer.importtask')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importer.student')),
            ],
            options={
                'ordering': ['enrolment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
